apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      serviceAccountName: argocd-sa  # Using the newly created ServiceAccount
      containers:
      - name: flaskdemo
        image: vijay1447/argocd-demo:17
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: flaskdemo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001  # Exposes the service on <minikube-ip>:30080
